# 字体
font_family      Maple Mono NF
bold_font        Maple Mono NF
italic_font      Maple Mono NF
bold_italic_font Maple Mono NF

font_size 14

# 中文 fallback
symbol_map U+4E00-U+9FFF Noto Sans CJK SC

# 光标
cursor_shape beam
cursor_blink_interval 0

# 滚动
scrollback_lines 10000

# Wayland
linux_display_server wayland

# 性能
repaint_delay 10
input_delay 3
sync_to_monitor yes

# 鼠标
copy_on_select yes

# URL
detect_urls yes

# terminal
term xterm-kitty

# shell integration
shell_integration enabled

# padding
window_padding_width 6

# 标签页
tab_bar_edge top

# 不透明度
background_opacity 0.70
